Expose more target group arguments and make load balancer and target group names respect the length limit automatically
cloudposse/terraform-aws-nlb pull request #32
Opened 2023-01-19 02:50 UTC by ento

## what
* Makes a few arguments of the `aws_lb_target_group` resource configurable through input variables of this module
* Ensures target group and load balancer names cannot exceed their max length
  * This mirrors (and was heavily inspired by) the changes that were made to cloudposse/terraform-aws-alb in https://github.com/cloudposse/terraform-aws-alb/pull/96

## why
* A project I was attempting to use this module in required changing these attributes
* I liked how cloudposse/terraform-aws-alb automatically limits the length of resource names so that I don't have to manually specify a name that fits the limit

## references
* [aws_lb_target_group resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group#argument-reference)

2023-06-26 12:33 UTC, jmerciercode commented on variables.tf
> +
Nice !

2024-03-07 00:25 UTC, ento commented
@hans-d I'm still interested in getting these changes merged. Can this be re-opened? Or will these be incorporated into the repo in some other way? I suppose the same question goes to the other PRs that were closed as stale that weren't really waiting on the PR author. (#35, #42)

2024-03-07 00:36 UTC, hans-d commented
feel free to reopen, but do get them in a reviewable shape (merge conflicts resolved, failing tests worked on). 
Otherwise they will be again closed due to staleness.

2024-03-07 00:44 UTC, joe-niland commented
@ento reopened as requested

Could you please run the following and commit the result?

```
make init
make readme
```

2024-03-14 03:13 UTC, Gowiem commented
/terratest

2024-03-14 03:16 UTC, Gowiem approved these changes
LGTM 👍

2024-03-14 03:20 UTC, Gowiem requested changes

2024-03-14 03:20 UTC, Gowiem commented on variables.tf
> +  default     = null
@ento we're getting the following error in our tests: 

```
TestExamplesComplete 2024-03-14T03:15:47Z logger.go:66: │ Error: Missing required argument
TestExamplesComplete 2024-03-14T03:15:47Z logger.go:66: │ 
TestExamplesComplete 2024-03-14T03:15:47Z logger.go:66: │   with module.nlb.aws_lb_target_group.default[0],
TestExamplesComplete 2024-03-14T03:15:47Z logger.go:66: │   on ../../main.tf line 177, in resource "aws_lb_target_group" "default":
TestExamplesComplete 2024-03-14T03:15:47Z logger.go:66: │  177:     type            = var.stickiness_type
TestExamplesComplete 2024-03-14T03:15:47Z logger.go:66: │ 
TestExamplesComplete 2024-03-14T03:15:47Z logger.go:66: │ The argument "stickiness.0.type" is required, but no definition was found.
```

So it seems regardless if `stickiness_enabled` is false, we need a value for this variable. That said... I don't think we need this variable as [the docs mention the only valid variable for this argument is `source_ip` for NLBs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group#stickiness). Would you mind removing this variable and hardcoding this value into the resource argument since this module is only for creating NLBs?

2024-04-10 23:46 UTC, ento commented on variables.tf
> +  default     = null
Sorry for the delay. Removed the `stickiness_type` variable. I also realized that `cookie_name` and `cookie_duration` attributes don't make sense when stickiness type is `source_ip` (they're for `app_cookie` and `lb_cookie` types respectively), so their variables have been removed as well.

2024-04-11 14:24 UTC, Gowiem commented
/terratest

2024-04-11 14:38 UTC, Gowiem requested changes
One last change and we'll get this shipped.

2024-04-11 14:38 UTC, Gowiem commented on variables.tf
> +variable "connection_termination" {
Ah damn, sorry about this, I should have caught it earlier, but can we rename to follow our naming practices?

```suggestion
variable "connection_termination_enabled" {
```

2024-04-11 20:19 UTC, ento commented on variables.tf
> +variable "connection_termination" {
:+1: Done in [9ce7192](https://github.com/cloudposse/terraform-aws-nlb/pull/32/commits/9ce7192e3bc0b1c9cf74356ae00c4092f07ebaba)

2024-04-11 20:26 UTC, Gowiem submitted a review, later dismissed

2024-04-11 20:27 UTC, Gowiem commented
/terratest

2024-04-11 20:27 UTC, Gowiem commented on variables.tf
> +variable "connection_termination" {
Thanks! Running tests now and should auto-merge when all pass, so check back soon for the new release version! Thanks for the contribution!

2024-10-17 17:48 UTC, ento commented
@Gowiem Could you run tests again? Didn't seem to have run the last time and I needed to resolve a merge conflict that appeared since then.

2024-10-30 15:35 UTC, Gowiem commented
/terratest

2024-10-30 18:30 UTC, Gowiem approved these changes
LGTM 👍

2024-10-30 18:31 UTC, Gowiem commented
Looks like my approval is not enough. Calling in the @cloudposse/engineering

2025-02-10 21:13 UTC, goruha approved these changes

2025-02-10 21:16 UTC, goruha commented
@ento could you pls update the base branch? 
after that, we will merge the PR if tests will pass

2025-03-20 09:33 UTC, goruha approved these changes

2025-03-20 09:37 UTC, merged

2025-03-20 11:16 UTC, goruha commented
<!-- release-pr-comment:207130570 -->
  These changes were released in [v0.18.1](https://github.com/cloudposse/terraform-aws-nlb/releases/tag/v0.18.1).