feat: add health_check_timeout option
cloudposse/terraform-aws-nlb pull request #54
Opened 2024-03-05 20:49 UTC by rkul

## what

Add health check timeout option

## why

Impossible to set health check interval to less than 10 seconds, because it should be less than health check timeout

## references

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html

<img width="501" alt="image" src="https://github.com/cloudposse/terraform-aws-nlb/assets/5493637/d140bfd4-5472-4b2d-a8b8-7ab9bbec2f20">

2024-03-05 21:05 UTC, soar approved these changes

2024-03-05 22:31 UTC, hans-d requested changes

2024-03-05 22:31 UTC, hans-d commented on variables.tf
> +  default     = 10
Prevent providing a default that is not matching the default from aws. Better to have the default being null, keeping it backward compatible.

2024-03-06 07:56 UTC, rkul commented on variables.tf
> +  default     = 10
@hans-d yeah, makes sense, fixed

2024-03-06 12:24 UTC, soar approved these changes

2024-03-06 15:38 UTC, rkul commented
/terratest

2024-03-07 00:05 UTC, hans-d commented
/terratest

2024-03-07 00:15 UTC, hans-d approved these changes

2024-03-07 00:15 UTC, merged